importtype{Metadata}from"next";
import"./globals.css";

exportconstmetadata:Metadata={
title:"Percept-Anti-TutorialHellPlatform",
description:"Transformpassivelearnersintoconfident,skilleddevelopersthroughchallenge-basedlearning",
keywords:["coding","programming","tutorials","challenges","webdevelopment","JavaScript","React"],
authors:[{name:"PerceptTeam"}],
openGraph:{
title:"Percept-EscapeTutorialHall",
description:"Realchallengesforrealdevelopers.Nohand-holding,justproblem-solving.",
type:"website",
locale:"en_US",
},
twitter:{
card:"summary_large_image",
title:"Percept-Anti-TutorialHellPlatform",
description:"Transformfrompassivelearnertoconfidentdeveloper",
},
robots:{
index:true,
follow:true,
},
};

exportdefaultfunctionRootLayout({
children,
}:Readonly<{
children:React.ReactNode;
}>){
return(
<htmllang="en">
<bodyclassName="antialiased">
{children}
</body>
</html>
);
}