importLinkfrom'next/link';

exportdefaultfunctionDemoPage(){
return(
<divclassName="min-h-screenbg-gradient-to-brfrom-blue-50via-whiteto-indigo-50">
{/*Header*/}
<headerclassName="relativez-10">
<divclassName="max-w-7xlmx-autopx-4sm:px-6lg:px-8">
<divclassName="flexjustify-betweenitems-centerpy-6">
<divclassName="flexitems-center">
<h1className="text-2xlfont-boldtext-gray-900">Percept</h1>
</div>
<divclassName="flexitems-centerspace-x-4">
<Link
href="#demo"
className="text-gray-700hover:text-gray-900font-mediumtransition-colors"
>
SignIn
</Link>
<Link
href="#demo"
className="bg-blue-600hover:bg-blue-700text-whitefont-mediumpy-2px-4rounded-lgtransition-colors"
>
GetStarted
</Link>
</div>
</div>
</div>
</header>

{/*HeroSection*/}
<mainclassName="relative">
<divclassName="max-w-7xlmx-autopx-4sm:px-6lg:px-8pt-20pb-32">
<divclassName="text-center">
<h1className="text-5xlmd:text-6xlfont-boldtext-gray-900mb-6">
Escape
<spanclassName="text-blue-600">TutorialHell</span>
</h1>
<pclassName="text-xlmd:text-2xltext-gray-600mb-8max-w-3xlmx-auto">
Transformfrompassivelearnertoconfidentdeveloperthrough
<strong>real-worldchallenges</strong>thatbuildgenuineproblem-solvingskills.
</p>
<divclassName="flexflex-colsm:flex-rowgap-4justify-centeritems-centermb-12">
<Link
href="#demo"
className="bg-blue-600hover:bg-blue-700text-whitefont-semiboldpy-4px-8rounded-lgtext-lgtransition-allduration-300shadow-lghover:shadow-xltransformhover:-translate-y-1"
>
StartYourJourney
</Link>
<Link
href="#features"
className="text-gray-700hover:text-gray-900font-semiboldpy-4px-8rounded-lgtext-lgtransition-colorsborder-2border-gray-300hover:border-gray-400"
>
LearnMore→
</Link>
</div>

{/*SocialProof*/}
<divclassName="flexflex-colsm:flex-rowitems-centerjustify-centergap-8text-gray-600">
<divclassName="flexitems-center">
<spanclassName="text-2xlmr-2">⚡</span>
<spanclassName="font-medium">500+Challenges</span>
</div>
<divclassName="flexitems-center">
<spanclassName="text-2xlmr-2">👥</span>
<spanclassName="font-medium">10,000+Developers</span>
</div>
<divclassName="flexitems-center">
<spanclassName="text-2xlmr-2">🏆</span>
<spanclassName="font-medium">95%SuccessRate</span>
</div>
</div>
</div>
</div>

{/*DemoAlert*/}
<sectionclassName="py-12bg-blue-600">
<divclassName="max-w-4xlmx-autotext-centerpx-4sm:px-6lg:px-8">
<h2className="text-2xlmd:text-3xlfont-boldtext-whitemb-4">
🚀EnhancedUIShowcase
</h2>
<pclassName="text-lgtext-blue-100mb-6">
ProfessionalUIimprovementsforthePerceptplatform
</p>
<divclassName="bg-white/10rounded-lgp-6text-leftmax-w-2xlmx-auto">
<h3className="font-semiboldtext-whitemb-3">✅ImplementedFeatures:</h3>
<ulclassName="text-blue-100space-y-1text-sm">
<li>•Fixedauthentication404errors</li>
<li>•Enhancedlandingpagedesign</li>
<li>•Addederrorhandling&ratelimiting</li>
<li>•Createdrichdashboard</li>
<li>•Builtchallenges&profilepages</li>
<li>•Addedanalytics&progresstracking</li>
</ul>
</div>
</div>
</section>

{/*FeaturesSection*/}
<sectionid="features"className="py-20bg-white">
<divclassName="max-w-7xlmx-autopx-4sm:px-6lg:px-8">
<divclassName="text-centermb-16">
<h2className="text-3xlmd:text-4xlfont-boldtext-gray-900mb-4">
WhyPerceptWorks
</h2>
<pclassName="text-xltext-gray-600max-w-2xlmx-auto">
Ouranti-tutorialapproachbuildsrealdeveloperskills
</p>
</div>

<divclassName="gridgrid-cols-1md:grid-cols-3gap-8">
<divclassName="text-centerp-6">
<divclassName="w-16h-16bg-blue-100rounded-fullflexitems-centerjustify-centermx-automb-4">
<spanclassName="text-2xl">🎯</span>
</div>
<h3className="text-xlfont-semiboldtext-gray-900mb-2">
NoHand-Holding
</h3>
<pclassName="text-gray-600">
Getproblems,notsolutions.Learntoresearchandbuildindependently.
</p>
</div>

<divclassName="text-centerp-6">
<divclassName="w-16h-16bg-green-100rounded-fullflexitems-centerjustify-centermx-automb-4">
<spanclassName="text-2xl">🏗️</span>
</div>
<h3className="text-xlfont-semiboldtext-gray-900mb-2">
RealChallenges
</h3>
<pclassName="text-gray-600">
SolveactualproblemsacrossHTML,CSS,JavaScript,React,andAPIs.
</p>
</div>

<divclassName="text-centerp-6">
<divclassName="w-16h-16bg-purple-100rounded-fullflexitems-centerjustify-centermx-automb-4">
<spanclassName="text-2xl">🤖</span>
</div>
<h3className="text-xlfont-semiboldtext-gray-900mb-2">
AI-PoweredHints
</h3>
<pclassName="text-gray-600">
Getprogressivenudgeswithoutspoilingsolutions.
</p>
</div>
</div>
</div>
</section>

{/*CTASection*/}
<sectionclassName="py-20bg-blue-600">
<divclassName="max-w-4xlmx-autotext-centerpx-4sm:px-6lg:px-8">
<h2className="text-3xlmd:text-4xlfont-boldtext-whitemb-4">
ReadytoBreakFreefromTutorialHell?
</h2>
<pclassName="text-xltext-blue-100mb-8">
Joindeveloperstransformingtheirskillsthroughrealproblemsolving
</p>
<Link
href="#demo"
className="bg-whitehover:bg-gray-100text-blue-600font-semiboldpy-4px-8rounded-lgtext-lgtransition-colorsshadow-lghover:shadow-xlinline-block"
>
StartSolvingRealProblems
</Link>
</div>
</section>
</main>

{/*Footer*/}
<footerclassName="bg-gray-900text-whitepy-12">
<divclassName="max-w-7xlmx-autopx-4sm:px-6lg:px-8">
<divclassName="text-center">
<h3className="text-2xlfont-boldmb-4">Percept</h3>
<pclassName="text-gray-400mb-4">
Theanti-tutorialhellplatformforconfidentdevelopers
</p>
</div>
</div>
</footer>
</div>
);
}