//components/MobileNav.tsx

"useclient";

importReact,{useState}from"react";
import{AnimatePresence,motion}from"framer-motion";
import{Menu,X}from"lucide-react";
importLinkfrom"next/link";
import{Button}from"@/components/ui/button";
import{ThemeToggle}from"@/components/theme-toggle";
import{GlobalSearch}from"@/components/ui/global-search";

exportdefaultfunctionMobileNav(){
const[isMobileMenuOpen,setIsMobileMenuOpen]=useState(false);

return(
<>
{/*Mobilemenubutton*/}
<divclassName="md:hiddenflexitems-centerspace-x-2">
<GlobalSearch/>
<ThemeToggle/>
<Button
variant="outline"
size="icon"
onClick={()=>setIsMobileMenuOpen(!isMobileMenuOpen)}
>
{isMobileMenuOpen?(
<XclassName="h-4w-4"/>
):(
<MenuclassName="h-4w-4"/>
)}
</Button>
</div>

{/*MobileNavigation*/}
<AnimatePresence>
{isMobileMenuOpen&&(
<motion.div
initial={{opacity:0,height:0}}
animate={{opacity:1,height:"auto"}}
exit={{opacity:0,height:0}}
className="md:hiddenpy-4border-tborder-gray-200dark:border-gray-700overflow-hidden"
>
<divclassName="flexflex-colspace-y-2">
<Link
href="/learn"
className="px-4py-2text-gray-600dark:text-gray-300hover:text-gray-900dark:hover:text-whitetransition-colors"
onClick={()=>setIsMobileMenuOpen(false)}
>
LearningPortal
</Link>
<Link
href="/challenges"
className="px-4py-2text-gray-600dark:text-gray-300hover:text-gray-900dark:hover:text-whitetransition-colors"
onClick={()=>setIsMobileMenuOpen(false)}
>
Challenges
</Link>
<Link
href="/app"
className="px-4py-2text-gray-600dark:text-gray-300hover:text-gray-900dark:hover:text-whitetransition-colors"
onClick={()=>setIsMobileMenuOpen(false)}
>
SignIn
</Link>
<Button
asChild
className="mx-4bg-gradient-to-rfrom-blue-600to-purple-600"
>
<Link
href="/app"
onClick={()=>setIsMobileMenuOpen(false)}
>
GetStarted
</Link>
</Button>
</div>
</motion.div>
)}
</AnimatePresence>
</>
);
}