import{NextRequest,NextResponse}from'next/server';

exportasyncfunctionGET(request:NextRequest){
try{
//Healthcheckendpoint
returnNextResponse.json({
status:'healthy',
timestamp:newDate().toISOString(),
version:'1.0.0',
environment:process.env.NODE_ENV
});
}catch(error){
console.error('Healthcheckerror:',error);
returnNextResponse.json(
{error:'Serviceunavailable'},
{status:503}
);
}
}