'useclient';

import{useEffect}from'react';
importLinkfrom'next/link';

exportdefaultfunctionError({
error,
reset,
}:{
error:Error&{digest?:string};
reset:()=>void;
}){
useEffect(()=>{
//Logtheerrortoyourerrorreportingservice
console.error('Applicationerror:',error);
},[error]);

return(
<divclassName="min-h-screenbg-gradient-to-brfrom-red-50to-orange-100flexitems-centerjustify-centerpx-4">
<divclassName="max-w-mdw-fulltext-center">
<divclassName="mb-8">
<divclassName="text-8xlmb-4">⚠️</div>
<h1className="text-4xlfont-boldtext-gray-900mb-2">Somethingwentwrong</h1>
<pclassName="text-lgtext-gray-600mb-8">
Anunexpectederroroccurred.Ourteamhasbeennotified.
</p>
{process.env.NODE_ENV==='development'&&(
<detailsclassName="mt-4p-4bg-red-100rounded-lgtext-lefttext-sm">
<summaryclassName="cursor-pointerfont-mediumtext-red-800">
ErrorDetails(Development)
</summary>
<preclassName="mt-2text-red-700whitespace-pre-wrap">
{error.message}
</pre>
</details>
)}
</div>

<divclassName="space-y-4">
<button
onClick={reset}
className="blockw-fullbg-blue-600hover:bg-blue-700text-whitefont-mediumpy-3px-6rounded-lgtransition-colors"
>
TryAgain
</button>
<Link
href="/"
className="blocktext-gray-700hover:text-gray-900font-mediumpy-3px-6rounded-lgborderborder-gray-300hover:border-gray-400transition-colors"
>
GoHome
</Link>
</div>
</div>
</div>
);
}