importtype{Metadata}from"next";
import{ClerkProvider}from'@clerk/nextjs';
import"./globals.css";
import{ThemeProvider}from"@/components/theme-provider";
import{Toaster}from"react-hot-toast";

exportconstmetadata:Metadata={
title:"Percept-Anti-TutorialHellPlatform",
description:"Transformpassivelearnersintoconfident,skilleddevelopersthroughchallenge-basedlearning",
keywords:["coding","programming","tutorials","challenges","webdevelopment","JavaScript","React"],
authors:[{name:"PerceptTeam"}],
openGraph:{
title:"Percept-EscapeTutorialHell",
description:"Realchallengesforrealdevelopers.Nohand-holding,justproblem-solving.",
type:"website",
locale:"en_US",
},
twitter:{
card:"summary_large_image",
title:"Percept-Anti-TutorialHellPlatform",
description:"Transformfrompassivelearnertoconfidentdeveloper",
},
robots:{
index:true,
follow:true,
},
};

exportdefaultfunctionRootLayout({
children,
}:Readonly<{
children:React.ReactNode;
}>){
return(
<ClerkProvider
appearance={{
elements:{
formButtonPrimary:
"bg-blue-600hover:bg-blue-700text-whitefont-mediumpy-2px-4rounded-lgtransition-colors",
card:"shadow-xlborder-0rounded-2xlbg-white",
headerTitle:"text-2xlfont-semiboldtext-gray-900",
headerSubtitle:"text-gray-600",
socialButtonsBlockButton:
"borderborder-gray-300hover:bg-gray-50text-gray-700font-mediumrounded-lgtransition-colors",
formFieldInput:
"borderborder-gray-300rounded-lgpx-3py-2focus:outline-nonefocus:ring-2focus:ring-blue-500focus:border-transparent",
footerActionLink:"text-blue-600hover:text-blue-700font-medium",
dividerLine:"bg-gray-200",
dividerText:"text-gray-500",
formFieldLabel:"text-gray-700font-medium",
identityPreviewText:"text-gray-600",
identityPreviewEditButton:"text-blue-600hover:text-blue-700"
}
}}
>
<htmllang="en"suppressHydrationWarning>
<head>
<linkrel="preconnect"href="https://fonts.googleapis.com"/>
<link
rel="preconnect"
href="https://fonts.gstatic.com"
crossOrigin="anonymous"
/>
</head>
<bodyclassName="min-h-screenbg-backgroundfont-sansantialiased">
<ThemeProvider
attribute="class"
defaultTheme="system"
enableSystem
disableTransitionOnChange
>
{children}
<Toaster
position="top-right"
toastOptions={{
duration:4000,
style:{
background:"#363636",
color:"#fff",
},
}}
/>
</ThemeProvider>
</body>
</html>
</ClerkProvider>
);
}
