import{auth}from'@clerk/nextjs/server';
import{redirect}from'next/navigation';
import{UserButton}from'@clerk/nextjs';
importLinkfrom'next/link';

exportdefaultasyncfunctionProfilePage(){
const{userId}=awaitauth();

if(!userId){
redirect('/sign-in');
}

return(
<divclassName="min-h-screenbg-gray-50">
{/*Header*/}
<headerclassName="bg-whiteshadow-smborder-bborder-gray-200">
<divclassName="max-w-7xlmx-autopx-4sm:px-6lg:px-8">
<divclassName="flexjustify-betweenitems-centerh-16">
<divclassName="flexitems-centerspace-x-8">
<Linkhref="/dashboard"className="flexitems-center">
<h1className="text-2xlfont-boldtext-gray-900">Percept</h1>
<spanclassName="ml-2text-smtext-gray-500">Profile</span>
</Link>
<navclassName="hiddenmd:flexspace-x-6">
<Linkhref="/dashboard"className="text-gray-600hover:text-gray-900font-mediumtransition-colors">
Dashboard
</Link>
<Linkhref="/challenges"className="text-gray-600hover:text-gray-900font-mediumtransition-colors">
Challenges
</Link>
<Linkhref="/profile"className="text-blue-600font-medium">
Profile
</Link>
<Linkhref="/analytics"className="text-gray-600hover:text-gray-900font-mediumtransition-colors">
Analytics
</Link>
</nav>
</div>
<divclassName="flexitems-centerspace-x-4">
<UserButton
appearance={{
elements:{
avatarBox:"w-10h-10"
}
}}
/>
</div>
</div>
</div>
</header>

{/*MainContent*/}
<mainclassName="max-w-4xlmx-autopx-4sm:px-6lg:px-8py-8">
<divclassName="mb-8">
<h2className="text-3xlfont-boldtext-gray-900mb-2">
YourProfile⚙️
</h2>
<pclassName="text-lgtext-gray-600">
Customizeyourlearningexperienceandtrackyourdevelopmentjourney.
</p>
</div>

{/*ProfileOverview*/}
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6mb-8">
<divclassName="flexitems-centerspace-x-6">
<divclassName="w-20h-20bg-blue-100rounded-fullflexitems-centerjustify-center">
<spanclassName="text-3xl">👨‍💻</span>
</div>
<divclassName="flex-1">
<h3className="text-xlfont-semiboldtext-gray-900">DeveloperProfile</h3>
<pclassName="text-gray-600mb-2">MembersinceDecember2024</p>
<divclassName="flexitems-centerspace-x-4">
<spanclassName="bg-blue-100text-blue-800text-smfont-mediumpx-3py-1rounded-full">
Level3Developer
</span>
<spanclassName="text-smtext-gray-600">1,420XP</span>
</div>
</div>
</div>
</div>

{/*QuickStats*/}
<divclassName="gridgrid-cols-1md:grid-cols-3gap-6mb-8">
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6text-center">
<divclassName="text-3xlfont-boldtext-blue-600mb-2">12</div>
<divclassName="text-gray-600">ChallengesCompleted</div>
</div>
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6text-center">
<divclassName="text-3xlfont-boldtext-green-600mb-2">7</div>
<divclassName="text-gray-600">DayStreak</div>
</div>
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6text-center">
<divclassName="text-3xlfont-boldtext-purple-600mb-2">5</div>
<divclassName="text-gray-600">SkillsMastered</div>
</div>
</div>

<divclassName="gridgrid-cols-1lg:grid-cols-2gap-8">
{/*LearningPreferences*/}
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6">
<h3className="text-lgfont-semiboldtext-gray-900mb-4">LearningPreferences</h3>
<divclassName="space-y-4">
<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-2">
PreferredDifficultyLevel
</label>
<selectclassName="w-fullborderborder-gray-300rounded-lgpx-3py-2focus:outline-nonefocus:ring-2focus:ring-blue-500">
<option>Beginner</option>
<optionselected>Intermediate</option>
<option>Advanced</option>
<option>Mixed</option>
</select>
</div>

<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-2">
FocusAreas
</label>
<divclassName="space-y-2">
{[
{name:'FrontendDevelopment',checked:true},
{name:'BackendDevelopment',checked:false},
{name:'FullStack',checked:true},
{name:'MobileDevelopment',checked:false}
].map((area,index)=>(
<labelkey={index}className="flexitems-center">
<input
type="checkbox"
checked={area.checked}
className="roundedborder-gray-300text-blue-600focus:ring-blue-500"
/>
<spanclassName="ml-2text-smtext-gray-700">{area.name}</span>
</label>
))}
</div>
</div>

<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-2">
DailyLearningGoal
</label>
<selectclassName="w-fullborderborder-gray-300rounded-lgpx-3py-2focus:outline-nonefocus:ring-2focus:ring-blue-500">
<option>30minutes</option>
<optionselected>1hour</option>
<option>2hours</option>
<option>3+hours</option>
</select>
</div>
</div>
</div>

{/*Achievements*/}
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6">
<h3className="text-lgfont-semiboldtext-gray-900mb-4">Achievements🏆</h3>
<divclassName="space-y-4">
{[
{
title:"FirstSteps",
description:"Completedyourfirstchallenge",
earned:true,
icon:"🎯",
date:"Dec15,2024"
},
{
title:"StreakMaster",
description:"Maintaineda7-daylearningstreak",
earned:true,
icon:"🔥",
date:"Dec18,2024"
},
{
title:"JavaScriptNinja",
description:"Completed5JavaScriptchallenges",
earned:true,
icon:"⚡",
date:"Dec20,2024"
},
{
title:"ProblemSolver",
description:"Solved10challengeswithouthints",
earned:false,
icon:"🧠",
date:null
},
{
title:"FullStackExplorer",
description:"Completechallengesinfrontendandbackend",
earned:false,
icon:"🌟",
date:null
}
].map((achievement,index)=>(
<divkey={index}className={`flexitems-centerp-3rounded-lgborder-2${
achievement.earned?'border-green-200bg-green-50':'border-gray-200bg-gray-50'
}`}>
<divclassName="text-2xlmr-3">{achievement.icon}</div>
<divclassName="flex-1">
<h4className={`font-medium${achievement.earned?'text-green-900':'text-gray-500'}`}>
{achievement.title}
</h4>
<pclassName={`text-sm${achievement.earned?'text-green-700':'text-gray-500'}`}>
{achievement.description}
</p>
{achievement.date&&(
<pclassName="text-xstext-green-600mt-1">Earnedon{achievement.date}</p>
)}
</div>
{achievement.earned&&(
<divclassName="text-green-600">
<svgclassName="w-5h-5"fill="currentColor"viewBox="002020">
<pathfillRule="evenodd"d="M16.7075.293a1100101.414l-88a11001-1.4140l-4-4a110011.414-1.414L812.586l7.293-7.293a110011.4140z"clipRule="evenodd"/>
</svg>
</div>
)}
</div>
))}
</div>
</div>
</div>

{/*NotificationSettings*/}
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6mt-8">
<h3className="text-lgfont-semiboldtext-gray-900mb-4">NotificationSettings</h3>
<divclassName="space-y-4">
{[
{name:'Dailylearningreminders',description:'Getremindedtopracticecodingdaily',enabled:true},
{name:'Newchallengenotifications',description:'Benotifiedwhennewchallengesareadded',enabled:true},
{name:'Achievementcelebrations',description:'Celebratewhenyouearnnewachievements',enabled:true},
{name:'Weeklyprogressreports',description:'Receiveweeklysummariesofyourprogress',enabled:false},
{name:'Communityupdates',description:'Updatesaboutnewfeaturesandcommunityevents',enabled:false}
].map((setting,index)=>(
<divkey={index}className="flexitems-centerjustify-betweenp-3borderborder-gray-200rounded-lg">
<divclassName="flex-1">
<h4className="font-mediumtext-gray-900">{setting.name}</h4>
<pclassName="text-smtext-gray-600">{setting.description}</p>
</div>
<labelclassName="relativeinline-flexitems-centercursor-pointer">
<inputtype="checkbox"className="sr-onlypeer"checked={setting.enabled}/>
<divclassName="w-11h-6bg-gray-200peer-focus:outline-nonepeer-focus:ring-4peer-focus:ring-blue-300rounded-fullpeerpeer-checked:after:translate-x-fullpeer-checked:after:border-whiteafter:content-['']after:absoluteafter:top-[2px]after:left-[2px]after:bg-whiteafter:border-gray-300after:borderafter:rounded-fullafter:h-5after:w-5after:transition-allpeer-checked:bg-blue-600"></div>
</label>
</div>
))}
</div>
</div>

{/*AccountActions*/}
<divclassName="bg-whiterounded-lgshadow-smborderborder-gray-200p-6mt-8">
<h3className="text-lgfont-semiboldtext-gray-900mb-4">AccountActions</h3>
<divclassName="space-y-4">
<buttonclassName="w-fullbg-blue-600hover:bg-blue-700text-whitefont-mediumpy-3px-4rounded-lgtransition-colors">
SaveChanges
</button>
<buttonclassName="w-fullbg-gray-100hover:bg-gray-200text-gray-700font-mediumpy-3px-4rounded-lgtransition-colors">
ExportProgressData
</button>
<buttonclassName="w-fullbg-red-50hover:bg-red-100text-red-600font-mediumpy-3px-4rounded-lgtransition-colors">
ResetAllProgress
</button>
</div>
</div>
</main>
</div>
);
}