--Insertinitialtechnologies
INSERTINTOtechnologies(name,slug,description,difficulty_level,color,is_active)VALUES
('HTML','html','HyperTextMarkupLanguage-thefoundationofwebcontent',1,'#e34c26',true),
('CSS','css','CascadingStyleSheets-stylingandlayoutforwebpages',1,'#1572B6',true),
('JavaScript','javascript','Dynamicprogramminglanguageforwebinteractivity',2,'#F7DF1E',true),
('TypeScript','typescript','TypedsupersetofJavaScriptforbetterdevelopmentexperience',2,'#3178C6',true),
('React','react','Component-basedJavaScriptlibraryforbuildinguserinterfaces',3,'#61DAFB',true),
('APIIntegration','api-integration','WorkingwithRESTAPIsandexternalservices',2,'#009688',true);

--Insertchallengecategories
INSERTINTOchallenge_categories(name,slug,description,sort_order,is_active)VALUES
('Layout&Structure','layout-structure','Buildingpagelayoutsandcontentstructure',1,true),
('Styling&Design','styling-design','VisualdesignandCSStechniques',2,true),
('InteractiveElements','interactive-elements','Userinteractionsanddynamiccontent',3,true),
('DataHandling','data-handling','WorkingwithdataandAPIs',4,true),
('Performance&Optimization','performance-optimization','Codeoptimizationandbestpractices',5,true);

--Insertinitialachievements
INSERTINTOachievements(name,description,icon,badge_color,points,criteria,is_active)VALUES
('FirstSteps','Completeyourfirstchallenge','🎯','#3B82F6',100,'{"type":"challenges_completed","value":1}',true),
('HTMLHero','Complete5HTMLchallenges','🌐','#E34C26',250,'{"type":"technology_challenges","technology":"html","value":5}',true),
('CSSMaster','Complete10CSSchallenges','🎨','#1572B6',500,'{"type":"technology_challenges","technology":"css","value":10}',true),
('JavaScriptNinja','Complete15JavaScriptchallenges','⚡','#F7DF1E',750,'{"type":"technology_challenges","technology":"javascript","value":15}',true),
('TypeScriptPro','Complete10TypeScriptchallenges','📘','#3178C6',600,'{"type":"technology_challenges","technology":"typescript","value":10}',true),
('ReactWizard','Complete20Reactchallenges','⚛️','#61DAFB',1000,'{"type":"technology_challenges","technology":"react","value":20}',true),
('APIExpert','Complete8APIIntegrationchallenges','🔌','#009688',400,'{"type":"technology_challenges","technology":"api-integration","value":8}',true),
('WeekWarrior','Completechallengesfor7consecutivedays','🔥','#F59E0B',300,'{"type":"streak","value":7}',true),
('ProblemSolver','Complete50challengestotal','🏆','#8B5CF6',2000,'{"type":"challenges_completed","value":50}',true),
('SpeedRunner','Completeachallengeinunder10minutes','⚡','#10B981',150,'{"type":"time_limit","value":10}',true);

--InsertsampleHTMLchallenges
DO$$
DECLARE
html_tech_idUUID;
layout_cat_idUUID;
styling_cat_idUUID;
BEGIN
--GettechnologyandcategoryIDs
SELECTidINTOhtml_tech_idFROMtechnologiesWHEREslug='html';
SELECTidINTOlayout_cat_idFROMchallenge_categoriesWHEREslug='layout-structure';
SELECTidINTOstyling_cat_idFROMchallenge_categoriesWHEREslug='styling-design';

--InsertHTMLchallenges
INSERTINTOchallenges(
title,slug,description,difficulty_level,category_id,technology_id,
problem_statement,requirements,starter_code,points,tags,is_published
)VALUES
(
'PersonalPortfolioHeader',
'personal-portfolio-header',
'Createaprofessionalheadersectionforapersonalportfoliowebsite',
1,
layout_cat_id,
html_tech_id,
'Buildaheadersectionthatincludesyourname,abrieftagline,andnavigationlinks.Thisheadershouldbesemanticandaccessible.',
ARRAY['UsesemanticHTML5elements','Includeproperheadinghierarchy','Addnavigationwithatleast4links','Includeaprofessionaltaglineorsubtitle'],
'<!DOCTYPEhtml>
<htmllang="en">
<head>
<metacharset="UTF-8">
<metaname="viewport"content="width=device-width,initial-scale=1.0">
<title>YourPortfolio</title>
</head>
<body>
<!--Buildyourheaderhere-->

</body>
</html>',
100,
ARRAY['html','semantic','portfolio','header'],
true
),
(
'ContactFormStructure',
'contact-form-structure',
'Buildacompletecontactformwithpropervalidationattributes',
1,
layout_cat_id,
html_tech_id,
'Createacontactformthatcollectsname,email,subject,andmessage.Useappropriateinputtypesandvalidationattributes.',
ARRAY['Useproperformstructure','Includeallrequiredinputtypes','Addproperlabelsforaccessibility','Includeclient-sidevalidationattributes'],
'<!DOCTYPEhtml>
<htmllang="en">
<head>
<metacharset="UTF-8">
<metaname="viewport"content="width=device-width,initial-scale=1.0">
<title>ContactForm</title>
</head>
<body>
<!--Createyourcontactformhere-->

</body>
</html>',
150,
ARRAY['html','forms','validation','accessibility'],
true
);
END$$;

--InsertsampleCSSchallenges
DO$$
DECLARE
css_tech_idUUID;
styling_cat_idUUID;
layout_cat_idUUID;
BEGIN
--GettechnologyandcategoryIDs
SELECTidINTOcss_tech_idFROMtechnologiesWHEREslug='css';
SELECTidINTOstyling_cat_idFROMchallenge_categoriesWHEREslug='styling-design';
SELECTidINTOlayout_cat_idFROMchallenge_categoriesWHEREslug='layout-structure';

--InsertCSSchallenges
INSERTINTOchallenges(
title,slug,description,difficulty_level,category_id,technology_id,
problem_statement,requirements,starter_code,points,tags,is_published
)VALUES
(
'ResponsiveCardComponent',
'responsive-card-component',
'Designaresponsivecardcomponentthatworksonallscreensizes',
2,
styling_cat_id,
css_tech_id,
'Createacardcomponentwithanimage,title,description,andbutton.Makeitresponsiveandvisuallyappealing.',
ARRAY['UseCSSGridorFlexboxforlayout','Implementresponsivedesign','Addhovereffects','Includeproperspacingandtypography'],
'<!DOCTYPEhtml>
<htmllang="en">
<head>
<metacharset="UTF-8">
<metaname="viewport"content="width=device-width,initial-scale=1.0">
<title>CardComponent</title>
<style>
/*AddyourCSShere*/

</style>
</head>
<body>
<divclass="card">
<imgsrc="https://picsum.photos/300/200"alt="Cardimage">
<divclass="card-content">
<h2>CardTitle</h2>
<p>Thisisthecarddescriptionthatshouldbestylednicely.</p>
<button>LearnMore</button>
</div>
</div>
</body>
</html>',
200,
ARRAY['css','responsive','components','layout'],
true
);
END$$;

--InsertsampleJavaScriptchallenges
DO$$
DECLARE
js_tech_idUUID;
interactive_cat_idUUID;
BEGIN
--GettechnologyandcategoryIDs
SELECTidINTOjs_tech_idFROMtechnologiesWHEREslug='javascript';
SELECTidINTOinteractive_cat_idFROMchallenge_categoriesWHEREslug='interactive-elements';

--InsertJavaScriptchallenges
INSERTINTOchallenges(
title,slug,description,difficulty_level,category_id,technology_id,
problem_statement,requirements,starter_code,points,tags,is_published
)VALUES
(
'TodoListManager',
'todo-list-manager',
'Buildafunctionaltodolistwithadd,complete,anddeletefunctionality',
2,
interactive_cat_id,
js_tech_id,
'Createatodolistwhereuserscanaddnewtasks,markthemascomplete,anddeletethem.Noframeworksallowed-vanillaJavaScriptonly.',
ARRAY['Addnewtodosviainputfield','Togglecompletionstatus','Deleteindividualtodos','PersiststateinlocalStorage'],
'<!DOCTYPEhtml>
<htmllang="en">
<head>
<metacharset="UTF-8">
<metaname="viewport"content="width=device-width,initial-scale=1.0">
<title>TodoList</title>
<style>
body{font-family:Arial,sans-serif;max-width:600px;margin:0auto;padding:20px;}
.todo-item{margin:10px0;padding:10px;border:1pxsolid#ddd;}
.completed{text-decoration:line-through;opacity:0.6;}
button{margin-left:10px;}
</style>
</head>
<body>
<h1>MyTodoList</h1>
<inputtype="text"id="todoInput"placeholder="Addanewtodo...">
<buttononclick="addTodo()">Add</button>
<divid="todoList"></div>

<script>
//AddyourJavaScriptcodehere

</script>
</body>
</html>',
250,
ARRAY['javascript','dom','events','localStorage'],
true
);
END$$;