"useclient"

import*asReactfrom"react"
import*asDialogPrimitivefrom"@radix-ui/react-dialog"
import{XIcon}from"lucide-react"

import{cn}from"@/lib/utils"

functionDialog({
...props
}:React.ComponentProps<typeofDialogPrimitive.Root>){
return<DialogPrimitive.Rootdata-slot="dialog"{...props}/>
}

functionDialogTrigger({
...props
}:React.ComponentProps<typeofDialogPrimitive.Trigger>){
return<DialogPrimitive.Triggerdata-slot="dialog-trigger"{...props}/>
}

functionDialogPortal({
...props
}:React.ComponentProps<typeofDialogPrimitive.Portal>){
return<DialogPrimitive.Portaldata-slot="dialog-portal"{...props}/>
}

functionDialogClose({
...props
}:React.ComponentProps<typeofDialogPrimitive.Close>){
return<DialogPrimitive.Closedata-slot="dialog-close"{...props}/>
}

functionDialogOverlay({
className,
...props
}:React.ComponentProps<typeofDialogPrimitive.Overlay>){
return(
<DialogPrimitive.Overlay
data-slot="dialog-overlay"
className={cn(
"data-[state=open]:animate-indata-[state=closed]:animate-outdata-[state=closed]:fade-out-0data-[state=open]:fade-in-0fixedinset-0z-50bg-black/50",
className
)}
{...props}
/>
)
}

functionDialogContent({
className,
children,
showCloseButton=true,
...props
}:React.ComponentProps<typeofDialogPrimitive.Content>&{
showCloseButton?:boolean
}){
return(
<DialogPortaldata-slot="dialog-portal">
<DialogOverlay/>
<DialogPrimitive.Content
data-slot="dialog-content"
className={cn(
"bg-backgrounddata-[state=open]:animate-indata-[state=closed]:animate-outdata-[state=closed]:fade-out-0data-[state=open]:fade-in-0data-[state=closed]:zoom-out-95data-[state=open]:zoom-in-95fixedtop-[50%]left-[50%]z-50gridw-fullmax-w-[calc(100%-2rem)]translate-x-[-50%]translate-y-[-50%]gap-4rounded-lgborderp-6shadow-lgduration-200sm:max-w-lg",
className
)}
{...props}
>
{children}
{showCloseButton&&(
<DialogPrimitive.Close
data-slot="dialog-close"
className="ring-offset-backgroundfocus:ring-ringdata-[state=open]:bg-accentdata-[state=open]:text-muted-foregroundabsolutetop-4right-4rounded-xsopacity-70transition-opacityhover:opacity-100focus:ring-2focus:ring-offset-2focus:outline-hiddendisabled:pointer-events-none[&_svg]:pointer-events-none[&_svg]:shrink-0[&_svg:not([class*='size-'])]:size-4"
>
<XIcon/>
<spanclassName="sr-only">Close</span>
</DialogPrimitive.Close>
)}
</DialogPrimitive.Content>
</DialogPortal>
)
}

functionDialogHeader({className,...props}:React.ComponentProps<"div">){
return(
<div
data-slot="dialog-header"
className={cn("flexflex-colgap-2text-centersm:text-left",className)}
{...props}
/>
)
}

functionDialogFooter({className,...props}:React.ComponentProps<"div">){
return(
<div
data-slot="dialog-footer"
className={cn(
"flexflex-col-reversegap-2sm:flex-rowsm:justify-end",
className
)}
{...props}
/>
)
}

functionDialogTitle({
className,
...props
}:React.ComponentProps<typeofDialogPrimitive.Title>){
return(
<DialogPrimitive.Title
data-slot="dialog-title"
className={cn("text-lgleading-nonefont-semibold",className)}
{...props}
/>
)
}

functionDialogDescription({
className,
...props
}:React.ComponentProps<typeofDialogPrimitive.Description>){
return(
<DialogPrimitive.Description
data-slot="dialog-description"
className={cn("text-muted-foregroundtext-sm",className)}
{...props}
/>
)
}

export{
Dialog,
DialogClose,
DialogContent,
DialogDescription,
DialogFooter,
DialogHeader,
DialogOverlay,
DialogPortal,
DialogTitle,
DialogTrigger,
}
