"useclient";

importReact,{useState,useEffect}from"react";
import{motion,AnimatePresence}from"framer-motion";
import{
X,
ArrowRight,
ArrowLeft,
CheckCircle,
Sparkles,
Target,
Zap,
Trophy,
Users,
BookOpen,
Code2,
}from"lucide-react";
import{Button}from"@/components/ui/button";
import{Card,CardContent}from"@/components/ui/card";
import{Badge}from"@/components/ui/badge";

interfaceTourStep{
id:string;
title:string;
description:string;
icon:React.ElementType;
target?:string;
action?:{
text:string;
href:string;
};
highlight?:boolean;
}

consttourSteps:TourStep[]=[
{
id:"welcome",
title:"WelcometoPercept!",
description:
"Readytoescapetutorialhell?Let'sshowyouaroundourrevolutionarylearningplatform.",
icon:Sparkles,
highlight:true,
},
{
id:"philosophy",
title:"OurAnti-TutorialPhilosophy",
description:
"Wedon'tspoon-feedyoucode.Instead,you'llstruggle,research,andsolverealproblemsindependently.",
icon:Target,
target:"#philosophy-section",
},
{
id:"learning",
title:"InteractiveLearningPortal",
description:
"Startwithprogrammingfundamentals,thenprogressthroughHTML,CSS,JavaScript,andbeyond.",
icon:BookOpen,
action:{
text:"ExploreLearningPortal",
href:"/learn",
},
},
{
id:"challenges",
title:"Real-WorldChallenges",
description:
"Testyourskillswithhands-oncodingchallengesthatmirroractualdevelopmentwork.",
icon:Trophy,
action:{
text:"ViewChallenges",
href:"/challenges",
},
},
{
id:"community",
title:"JointheCommunity",
description:
"Connectwiththousandsofdeveloperswhoaremasteringcodingthroughstruggle-firstlearning.",
icon:Users,
},
{
id:"start",
title:"ReadytoBegin?",
description:
"Yourjourneytobecomingaconfidentdeveloperstartsnow.Nomorepassivelearning!",
icon:Zap,
action:{
text:"StartLearning",
href:"/learn/programming",
},
highlight:true,
},
];

exportfunctionWelcomeTour(){
const[isOpen,setIsOpen]=useState(false);
const[currentStep,setCurrentStep]=useState(0);
const[hasSeenTour,setHasSeenTour]=useState(false);

useEffect(()=>{
//Checkifuserhasseenthetourbefore
consttourCompleted=localStorage.getItem("welcome-tour-completed");
if(!tourCompleted){
//Showtourafterabriefdelay
consttimer=setTimeout(()=>{
setIsOpen(true);
},2000);
return()=>clearTimeout(timer);
}else{
setHasSeenTour(true);
}
},[]);

constnextStep=()=>{
if(currentStep<tourSteps.length-1){
setCurrentStep(currentStep+1);
}
};

constprevStep=()=>{
if(currentStep>0){
setCurrentStep(currentStep-1);
}
};

constcloseTour=()=>{
setIsOpen(false);
localStorage.setItem("welcome-tour-completed","true");
setHasSeenTour(true);
};

constrestartTour=()=>{
setCurrentStep(0);
setIsOpen(true);
};

constcurrentTourStep=tourSteps[currentStep];
constprogress=((currentStep+1)/tourSteps.length)*100;

if(hasSeenTour&&!isOpen){
return(
<motion.div
initial={{opacity:0,scale:0.8}}
animate={{opacity:1,scale:1}}
className="fixedbottom-6left-6z-40"
>
<Button
onClick={restartTour}
variant="outline"
size="sm"
className="bg-white/90backdrop-blur-smshadow-lghover:shadow-xltransition-allduration-200"
>
<BookOpenclassName="w-4h-4mr-2"/>
TourGuide
</Button>
</motion.div>
);
}

return(
<AnimatePresence>
{isOpen&&(
<>
{/*Backdrop*/}
<motion.div
initial={{opacity:0}}
animate={{opacity:1}}
exit={{opacity:0}}
className="fixedinset-0bg-black/60backdrop-blur-smz-50"
onClick={closeTour}
/>

{/*TourCard*/}
<motion.div
initial={{opacity:0,scale:0.8,y:50}}
animate={{opacity:1,scale:1,y:0}}
exit={{opacity:0,scale:0.8,y:50}}
transition={{type:"spring",duration:0.5}}
className="fixedtop-1/2left-1/2transform-translate-x-1/2-translate-y-1/2z-50w-fullmax-w-mdmx-4"
>
<CardclassName="shadow-2xlborder-0overflow-hidden">
{/*ProgressBar*/}
<divclassName="h-2bg-gray-100dark:bg-gray-800">
<motion.div
initial={{width:0}}
animate={{width:`${progress}%`}}
transition={{duration:0.3}}
className="h-fullbg-gradient-to-rfrom-blue-500to-purple-500"
/>
</div>

<CardContentclassName="p-6">
{/*Header*/}
<divclassName="flexitems-centerjustify-betweenmb-4">
<divclassName="flexitems-centergap-2">
<div
className={`
p-2rounded-lg${
currentTourStep.highlight
?"bg-gradient-to-rfrom-blue-500to-purple-500"
:"bg-blue-100dark:bg-blue-900"
}
`}
>
<currentTourStep.icon
className={`w-5h-5${
currentTourStep.highlight
?"text-white"
:"text-blue-600dark:text-blue-400"
}`}
/>
</div>
<Badgevariant="secondary"className="text-xs">
{currentStep+1}of{tourSteps.length}
</Badge>
</div>
<Button
variant="ghost"
size="sm"
onClick={closeTour}
className="h-8w-8p-0"
>
<XclassName="w-4h-4"/>
</Button>
</div>

{/*Content*/}
<motion.div
key={currentStep}
initial={{opacity:0,x:20}}
animate={{opacity:1,x:0}}
exit={{opacity:0,x:-20}}
transition={{duration:0.3}}
>
<h3className="text-xlfont-boldmb-3text-gray-900dark:text-white">
{currentTourStep.title}
</h3>
<pclassName="text-gray-600dark:text-gray-300mb-6leading-relaxed">
{currentTourStep.description}
</p>
</motion.div>

{/*ActionButton*/}
{currentTourStep.action&&(
<motion.div
initial={{opacity:0,y:10}}
animate={{opacity:1,y:0}}
transition={{delay:0.2}}
className="mb-6"
>
<Button
asChild
className="w-fullbg-gradient-to-rfrom-blue-600to-purple-600hover:from-blue-700hover:to-purple-700"
>
<ahref={currentTourStep.action.href}onClick={closeTour}>
{currentTourStep.action.text}
<ArrowRightclassName="w-4h-4ml-2"/>
</a>
</Button>
</motion.div>
)}

{/*Navigation*/}
<divclassName="flexitems-centerjustify-between">
<Button
variant="outline"
size="sm"
onClick={prevStep}
disabled={currentStep===0}
className="flexitems-centergap-2"
>
<ArrowLeftclassName="w-4h-4"/>
Previous
</Button>

<divclassName="flexgap-1">
{tourSteps.map((_,index)=>(
<button
key={index}
onClick={()=>setCurrentStep(index)}
className={`
w-2h-2rounded-fulltransition-allduration-200
${
index===currentStep
?"bg-blue-600scale-125"
:index<currentStep
?"bg-green-500"
:"bg-gray-300dark:bg-gray-600"
}
`}
/>
))}
</div>

{currentStep===tourSteps.length-1?(
<Button
size="sm"
onClick={closeTour}
className="flexitems-centergap-2bg-green-600hover:bg-green-700"
>
<CheckCircleclassName="w-4h-4"/>
GetStarted!
</Button>
):(
<Button
size="sm"
onClick={nextStep}
className="flexitems-centergap-2"
>
Next
<ArrowRightclassName="w-4h-4"/>
</Button>
)}
</div>

{/*SkipOption*/}
<divclassName="mt-4text-center">
<button
onClick={closeTour}
className="text-smtext-gray-500hover:text-gray-700dark:text-gray-400dark:hover:text-gray-200transition-colors"
>
Skiptour
</button>
</div>
</CardContent>
</Card>
</motion.div>
</>
)}
</AnimatePresence>
);
}
