import{SignUp}from'@clerk/nextjs';

exportdefaultfunctionSignUpPage(){
return(
<divclassName="min-h-screenflexitems-centerjustify-centerbg-gradient-to-brfrom-blue-50to-indigo-100px-4">
<divclassName="max-w-mdw-fullspace-y-8">
<divclassName="text-center">
<h1className="text-4xlfont-boldtext-gray-900mb-2">
JoinPercept
</h1>
<pclassName="text-lgtext-gray-600">
Startyourjourneyfromtutorialstoreal-worldskills
</p>
</div>
<divclassName="flexjustify-center">
<SignUp
appearance={{
elements:{
formButtonPrimary:
"bg-blue-600hover:bg-blue-700text-whitefont-mediumpy-2px-4rounded-lgtransition-colors",
card:"shadow-xlborder-0rounded-2xlbg-white",
headerTitle:"text-2xlfont-semiboldtext-gray-900",
headerSubtitle:"text-gray-600",
socialButtonsBlockButton:
"borderborder-gray-300hover:bg-gray-50text-gray-700font-mediumrounded-lgtransition-colors",
formFieldInput:
"borderborder-gray-300rounded-lgpx-3py-2focus:outline-nonefocus:ring-2focus:ring-blue-500focus:border-transparent",
footerActionLink:"text-blue-600hover:text-blue-700font-medium"
}
}}
/>
</div>
</div>
</div>
);
}